type: pipeline
$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
display_name: automobile-price-prediction-pipeline
experiment_name: automobile-price-experiment

inputs:
  raw_data:
    type: uri_file
    path: azureml:used-cars-data@latest

outputs:
  train_data:
    type: uri_folder 
  test_data:
    type: uri_folder 
  model_info_output_path:
    type: uri_folder 

settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:test-cluster

jobs:
  prep_data:
    type: command
    code: ../../../data-science/src
    command: python prep.py --raw_data ${{inputs.raw_data}} --train_data ${{outputs.train_data}} --test_data ${{outputs.test_data}}
    environment: azureml:used-cars-train-env@latest
    inputs:
      raw_data: ${{parent.inputs.raw_data}}
    outputs:
      train_data: ${{parent.outputs.train_data}}
      test_data: ${{parent.outputs.test_data}}

  sweep_step:
    type: sweep
    inputs:
      train_data: ${{parent.jobs.prep_data.outputs.train_data}}
      test_data: ${{parent.jobs.prep_data.outputs.test_data}}
    outputs:
      model_output: ${{parent.outputs.model_info_output_path}}
    sampling_algorithm: random
    trial:
      code: ../../../data-science/src
      command: >-
        python train.py 
        --train_data ${{inputs.train_data}} 
        --test_data ${{inputs.test_data}} 
        --n_estimators ${{search_space.n_estimators}} 
        --max_depth ${{search_space.max_depth}} 
        --model_output ${{outputs.model_output}}
      environment: azureml:used-cars-train-env@latest
      inputs:
        train_data: ${{sweep_step.inputs.train_data}}
        test_data: ${{sweep_step.inputs.test_data}}
      outputs:
        model_output: ${{sweep_step.outputs.model_output}}
    search_space:
      n_estimators:
        type: choice
        values: [10, 20, 30, 50]
      max_depth:
        type: choice
        values: [3, 5, 8, 10]
    objective:
      goal: minimize
      primary_metric: MSE
    limits:
      max_total_trials: 20
      max_concurrent_trials: 10
      timeout: 7200

  register_model:
    type: command
    code: ../../../data-science/src
    command: python register.py --model_name "used_cars_model" --model_path ${{inputs.model_path}} --model_info_output_path ${{outputs.model_info_output_path}}
    environment: azureml:used-cars-train-env@latest
    inputs:
      model_path: ${{parent.outputs.model_info_output_path}}
    outputs:
      model_info_output_path: ${{parent.outputs.model_info_output_path}}