$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: used-cars-train-env
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: ../../../data-science/environment/train-conda.yml
description: Training environment for the automobile price prediction model