$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_model
display_name: Train Model
type: command
inputs:
  train_data: 
    type: uri_folder
  test_data: 
    type: uri_folder
  n_estimators:
    type: integer
  max_depth:
    type: integer
outputs:
  model_output:
    type: uri_folder
code: ../../../data-science/src
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest
command: >-
  python train.py 
  --train_data ${{inputs.train_data}} 
  --test_data ${{inputs.test_data}} 
  --n_estimators ${{inputs.n_estimators}} 
  --max_depth ${{inputs.max_depth}} 
  --model_output ${{outputs.model_output}}